### ISSUE TITLE
[bug] problem with timezone

### ISSUE THREAD

**Issue by mglowacki100** [oronimbus/tactical-asset-allocation#4]
First of all great project! 
I've tried to run main.ipynb on google colab but this line `
ew = EqualWeights(assets, rebalance_dates).weights` gives me an error:
`TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize`
I've tried to fix it by `rebalance_dates = pd.bdate_range(start, end, freq="BM", tz='UTC')` but error appears further down in pipeline for line `bt = Backtester(all_strategies, "USD")` : `ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
`. Could you advise on this ?

**Comment by oronimbus** [comment]
could be due to your pandas or numpy version (I've updated the setup.cfg and maybe that caused an issue when launching in collab)? I've justed tested on a new machine using:
```
numpy~=2.0.2
pandas~=2.2.3
```

And it works fine!

**Comment by mglowacki100** [comment]
Thanks a lot!
One addtional dependency to add in requrements.txt (`matplotlib~=3.8.4`), because now google colab crashes at import matplotlib as on colab it is preinstalled in the version that works with numpy < 2. So workaround for this is google colab:
```
!pip install pytaa
!pip install matplotlib==3.8.4
->restart session (ctrl + M)
```
